#!/usr/bin/env bash
set -euo pipefail

# Build and deploy AveryOS runtime to Cloudflare Workers (production env).
# Requires Bun + Wrangler auth to already be configured.
#
# ⚠️  WARNING: This script will fail because the current build produces a Next.js
# app, not a Worker bundle. The wrangler.toml expects dist/worker.js, but
# `bun run build` (next build) does not create this file.
#
# See README.md for deployment alternatives (Vercel, Netlify, Cloudflare Pages).

# NOTE: This script is currently not functional because:
# 1. The codebase uses Node.js filesystem APIs (fs module) incompatible with Workers
# 2. No Worker bundle (dist/worker.js) is generated by the build process
# 3. The build produces a Next.js application, not a Worker entrypoint
#
# See wrangler.toml for more details on Workers compatibility requirements.

bun install
bun run build

# Ensure the expected Worker bundle exists before deploying.
if [ ! -f dist/worker.js ]; then
  echo "Error: dist/worker.js not found. Ensure your build produces dist/worker.js before deploying."
  echo "Consider deploying to Vercel/Netlify or using Cloudflare Pages adapter for Next.js instead."
# NOTE: wrangler.toml expects dist/worker.js but the Next.js build doesn't produce it.
# Ensure the expected Worker bundle exists before deploying.
if [ ! -f dist/worker.js ]; then
  echo "Error: dist/worker.js not found. The Next.js build does not produce a Worker bundle."
  echo "To deploy to Cloudflare Workers, you need to:"
  echo "  1. Use a Cloudflare/Next adapter that outputs a Worker-compatible bundle"
  echo "  2. Or build a Worker entrypoint (e.g., with esbuild) before deploying"
# Ensure the expected Worker bundle exists before deploying
if [ ! -f dist/worker.js ]; then
  echo "Error: dist/worker.js not found."
  echo "The current build produces a Next.js app, not a Cloudflare Worker."
  echo "Deploy to Vercel, Netlify, or Cloudflare Pages instead."
# Ensure the expected Worker bundle exists before deploying.
if [ ! -f dist/worker.js ]; then
  echo "Error: dist/worker.js not found. Ensure your build produces dist/worker.js before deploying."
  echo "The current build runs 'next build' which produces a Next.js app, not a Worker bundle."
  echo "Consider adding a Worker entrypoint or using a Next.js Cloudflare adapter."
  exit 1
fi

npx wrangler deploy --env production
