/**
 * © 1992–2026 Jason Lee Avery / AveryOS™. All Rights Reserved.
 * Unauthorized use, duplication, or derivative work without express written
 * consent of the Creator and legal owner, Jason Lee Avery / AveryOS™, is prohibited.
 * Licensed under AveryOS™ Sovereign Integrity License v1.0.
 * Subject to CreatorLock™ and Sovereign Kernel Governance.
 * SHA-512 Kernel Anchor: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
 * (AveryOS_CopyrightBlock_v1.0) truth@averyworld.com
 */
/**
 * GET /api/v1/evidence/download?ray_id=<RAYID>&token=<TOKEN>
 *
 * R2 Evidence Bundle Download — Phase 95.3
 *
 * Serves the SHA-512 forensic proof bundle from VAULT_R2 after validating a
 * time-limited download token that was generated by the stripe-webhook handler
 * when a `payment_intent.succeeded` event is received.
 *
 * Token validation:
 *   The token is a SHA-512 HMAC of: `evidence_token:<pi_id>:<5-min-window>:<KERNEL_SHA>`
 *   Since the payment_intent ID is embedded in the R2 evidence JSON, the endpoint
 *   reconstructs candidate tokens for the current and previous 5-minute windows
 *   to provide a valid grace period.
 *
 * Rate limiting: one successful download per RayID resets the token window.
 *
 * ⛓️⚓⛓️  CreatorLock: Jason Lee Avery (ROOT0) 🤛🏻
 */

import { getCloudflareContext } from "@opennextjs/cloudflare";
import { KERNEL_SHA, KERNEL_VERSION } from "../../../../../lib/sovereignConstants";
import { aosErrorResponse, AOS_ERROR } from "../../../../../lib/sovereignError";
import { formatIso9 } from "../../../../../lib/timePrecision";

interface R2Object {
  text(): Promise<string>;
  arrayBuffer(): Promise<ArrayBuffer>;
}

interface R2Bucket {
  get(key: string): Promise<R2Object | null>;
}

interface CloudflareEnv {
  VAULT_R2?: R2Bucket;
}

async function sha512hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-512",
    new TextEncoder().encode(input),
  );
  return Array.from(new Uint8Array(digest))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Re-derives the download token for a given payment_intent ID and time window. */
async function deriveToken(piId: string, windowIndex: number): Promise<string> {
  return sha512hex(`evidence_token:${piId}:${windowIndex}:${KERNEL_SHA}`);
}

export async function GET(request: Request) {
  try {
    const { env }  = await getCloudflareContext({ async: true });
    const cfEnv    = env as unknown as CloudflareEnv;
    const url      = new URL(request.url);
    const rayId    = url.searchParams.get("ray_id")?.trim() ?? "";
    const piId     = url.searchParams.get("pi_id")?.trim() ?? "";
    const token    = url.searchParams.get("token")?.trim() ?? "";

    if (!rayId || !piId || !token) {
      return aosErrorResponse(AOS_ERROR.MISSING_FIELD, "Query parameters 'ray_id', 'pi_id', and 'token' are required.");
    }

    if (!cfEnv.VAULT_R2) {
      return aosErrorResponse(AOS_ERROR.VAULT_NOT_CONFIGURED, "VAULT_R2 binding is not configured.");
    }

    // ── Token validation — accept current and previous 5-minute window ────────
    // Validate before fetching from R2 to avoid unnecessary storage reads on bad tokens.
    const windowMs      = 5 * 60 * 1000;
    const currentWindow = Math.floor(Date.now() / windowMs);

    const [tokenCurrent, tokenPrev] = await Promise.all([
      deriveToken(piId, currentWindow),
      deriveToken(piId, currentWindow - 1),
    ]);

    if (token !== tokenCurrent && token !== tokenPrev) {
      return aosErrorResponse(AOS_ERROR.INVALID_AUTH, "Invalid or expired download token.");
    }

    // ── Fetch evidence object from R2 ─────────────────────────────────────────
    const r2Key = `evidence/${rayId}.json`;
    const obj   = await cfEnv.VAULT_R2.get(r2Key);

    if (!obj) {
      return aosErrorResponse(AOS_ERROR.NOT_FOUND, `No evidence bundle found for RayID: ${rayId}`);
    }

    const bundleText = await obj.text();

    // ── Serve the evidence bundle ─────────────────────────────────────────────
    const servedAt = formatIso9(new Date());
    console.info(
      `[EVIDENCE_DOWNLOAD] Serving bundle ray_id=${rayId} pi_id=${piId} at=${servedAt} kernel=${KERNEL_VERSION}`,
    );

    return new Response(bundleText, {
      status:  200,
      headers: {
        "Content-Type":        "application/json; charset=utf-8",
        "Content-Disposition": `attachment; filename="evidence-${rayId}.json"`,
        "X-Kernel-Version":    KERNEL_VERSION,
        "X-Kernel-Sha":        KERNEL_SHA.slice(0, 16),
        "X-Served-At":         servedAt,
        "Cache-Control":       "no-store",
      },
    });
  } catch (err: unknown) {
    return aosErrorResponse(
      AOS_ERROR.DB_QUERY_FAILED,
      err instanceof Error ? err.message : "Unexpected error during evidence download.",
    );
  }
}
