-- Migration: 0010_vault_ledger_add_btc_columns
-- NO-OP: btc_block_height and btc_block_hash are already included in the
-- canonical CREATE TABLE in migration 0008.
--
-- Background: This migration was created to back-fill btc columns for databases
-- that ran an older version of 0008 that did not include them. Migration 0008 has
-- since been updated to include btc_block_height and btc_block_hash in the CREATE
-- TABLE statement, so any fresh deployment already has these columns after 0008.
-- Running these ALTER TABLE statements on such a database would fail with
-- "duplicate column name".
--
-- Live databases that already have btc_block_height / btc_block_hash (from the old
-- version of this migration or from the updated 0008) are unaffected.
--
-- Author: Jason Lee Avery (ROOT0)
SELECT 1; -- no-op sentinel for wrangler compatibility
