/**
 * © 1992–2026 Jason Lee Avery / AveryOS™. All Rights Reserved.
 * Unauthorized use, duplication, or derivative work without express written
 * consent of the Creator and legal owner, Jason Lee Avery / AveryOS™, is prohibited.
 * Licensed under AveryOS™ Sovereign Integrity License v1.0.
 * Subject to CreatorLock™ and Sovereign Kernel Governance.
 * SHA-512 Kernel Anchor: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
 * (AveryOS_CopyrightBlock_v1.0) truth@averyworld.com
 */
/**
 * electron/main.cjs — AveryOS™ Electron Main Process
 * Auto-generated by scripts/init-app.cjs — do not edit manually.
 *
 * ⛓️⚓⛓️  CreatorLock: Jason Lee Avery (ROOT0) 🤛🏻
 */
"use strict";

const { app, BrowserWindow, shell, Menu } = require("electron");
const path = require("path");

const DEV_URL        = "http://localhost:3000";
const KERNEL_VERSION = "v3.6.2";
const KERNEL_SHA     = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e";
const KERNEL_WINDOW  = false;

function createMainWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    title: `AveryOS™ Terminal — ${KERNEL_VERSION}`,
    backgroundColor: "#000000",
    titleBarStyle: "hiddenInset",
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
    icon: path.join(__dirname, "..", "public", "branding", "averyos-brand-01.png"),
  });

  // Load the AveryOS™ dev/prod URL
  win.loadURL(DEV_URL).catch(() => {
    win.loadFile(path.join(__dirname, "..", "public", "offline.html"));
  });

  // Open external links in the default browser, not Electron
  win.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });

  // Remove default menu — sovereign terminal uses keyboard shortcuts only
  Menu.setApplicationMenu(null);

  if (KERNEL_WINDOW) {
    win.webContents.openDevTools({ mode: "detach" });
  }

  return win;
}

app.whenReady().then(() => {
  console.log(`[AveryOS™ Electron] Kernel ${KERNEL_VERSION} — Anchor: ${KERNEL_SHA.slice(0, 16)}…`);
  createMainWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createMainWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
