const fs = require("fs");
const path = require("path");
const os = require("os");
const { compileCapsuleSignature } = require('./capsuleSignatureCompiler.cjs');

const SOVEREIGN_LOCK_PATH = path.join(process.cwd(), ".sovereign-lock");

// Cross-platform anchor salt path — generated by `npm run setup`
// Falls back to the legacy Windows USB path if the local file is absent.
const LOCAL_SALT_PATH = path.join(process.cwd(), ".anchor-salt");
const LEGACY_USB_PATH = "D:\\.averyos-anchor-salt.aossalt";

function resolveSaltPath() {
  let localExists = false;
  try { fs.accessSync(LOCAL_SALT_PATH); localExists = true; } catch {}
  if (localExists) return LOCAL_SALT_PATH;
  let legacyExists = false;
  try { fs.accessSync(LEGACY_USB_PATH); legacyExists = true; } catch {}
  if (legacyExists) return LEGACY_USB_PATH;
  return null;
}

function main() {
  console.log("⛓️⚓⛓️ INITIALIZING TRIPLE HANDSHAKE...");

  // 1. ANCHOR SALT CHECK
  const saltPath = resolveSaltPath();
  if (!saltPath) {
    console.error("❌ ANCHOR SALT ERROR: .anchor-salt not found.");
    console.log("   ACTION: Run 'npm run setup' to generate the anchor salt file.");
    console.log("   Legacy path (Windows USB): " + LEGACY_USB_PATH);
    process.exit(1);
  }
  console.log("✅ Anchor Salt Detected: " + saltPath);

  // 2. RESONANCE CALCULATION
  const salt = fs.readFileSync(saltPath, "utf8").trim();
  const hardwareId = `${os.hostname()}:${os.platform()}:${os.arch()}`;
  const trueHash = compileCapsuleSignature(hardwareId + salt);
  const requiredKey = `AVERY-SOV-2026-${trueHash}`;

  // 3. ARGUMENT AUDIT
  const args = process.argv.slice(2);
  const keyIndex = args.indexOf("--key");
  let providedKey = (keyIndex !== -1 && args[keyIndex + 1]) ? args[keyIndex + 1].toLowerCase() : "";

  if (providedKey !== requiredKey.toLowerCase()) {
    console.log("\n🔍 KERNEL TRUTH REPORT:");
    console.log(`   Machine ID: "${hardwareId}"`);
    console.log(`   Required Key for this node: ${requiredKey}`);
    process.exit(1);
  }

  // 4. LOCK GENESIS — merge with existing lock data if present
  let existing = {};
  try {
    existing = JSON.parse(fs.readFileSync(SOVEREIGN_LOCK_PATH, "utf8"));
  } catch { /* file doesn't exist yet */ }
  const _lockFd = fs.openSync(SOVEREIGN_LOCK_PATH, 'w');
  try {
    fs.writeSync(_lockFd, JSON.stringify({
      ...existing,
      locked: true,
      node: `${os.hostname()} (${os.platform()}/${os.arch()})`,
      hardware: hardwareId,
      salt_path: saltPath,
      physicalSaltVerified: true,
      last_auth_at: new Date().toISOString(),
    }, null, 2));
  } finally {
    fs.closeSync(_lockFd);
  }

  console.log("✅ Sovereign Authentication Successful. Node Physically Locked.");
}
main();

