# AveryOS™ MCP (Model Context Protocol) Bridge — scripts/mcp-server.ps1
#
# Links Copilot/Claude chat sessions directly to the local PC repository via
# a persistent MCP (Model Context Protocol) server backed by the Ollama ALM.
#
# Usage:
#   .\scripts\mcp-server.ps1 [-RepoPath <path>] [-OllamaEndpoint <url>] [-Port <int>] [-DryRun]
#
# Requirements:
#   • Ollama installed and running (ollama serve) with averyos-alm model
#   • Node.js ≥ 22 in PATH
#   • Repository cloned locally at -RepoPath (defaults to current directory)
#
# After starting, configure your AI client to connect to:
#   http://localhost:<Port>/mcp  (default: http://localhost:3737/mcp)
#
# ⛓️⚓⛓️  CreatorLock: Jason Lee Avery (ROOT0) 🤛🏻

param(
    [string]$RepoPath       = (Get-Location).Path,
    [string]$OllamaEndpoint = "http://localhost:11434",
    [string]$ModelName      = "averyos-alm",
    [int]$Port              = 3737,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# ── Constants ────────────────────────────────────────────────────────────────
$KERNEL_SHA     = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
$KERNEL_VERSION = "v3.6.2"
$CREATOR_LOCK   = "Jason Lee Avery (ROOT0) 🤛🏻"
$MCP_VERSION    = "2024-11-05"

# ── Helpers ──────────────────────────────────────────────────────────────────
function Write-AosLog {
    param([string]$Level, [string]$Message)
    $ts = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ")
    $prefix = switch ($Level) {
        "INFO"  { "✅" }
        "WARN"  { "⚠️ " }
        "ERROR" { "❌" }
        default { "  " }
    }
    Write-Host "$prefix [$ts] $Message"
}

function Test-OllamaRunning {
    try {
        $r = Invoke-WebRequest -Uri "$OllamaEndpoint/api/tags" -TimeoutSec 5 -ErrorAction Stop
        return $r.StatusCode -eq 200
    } catch { return $false }
}

function Test-ModelAvailable {
    param([string]$Model)
    try {
        $r   = Invoke-WebRequest -Uri "$OllamaEndpoint/api/tags" -TimeoutSec 5 -ErrorAction Stop
        $obj = $r.Content | ConvertFrom-Json
        return ($obj.models | Where-Object { $_.name -like "$Model*" }).Count -gt 0
    } catch { return $false }
}

# ── MCP Request Handler (Node.js inline server) ───────────────────────────────
# We write a temporary Node.js file that implements the MCP JSON-RPC 2.0 protocol
# and bridges tool calls to the local Ollama ALM.
function Write-McpServerScript {
    param([string]$ScriptPath)

    $script = @"
#!/usr/bin/env node
/**
 * AveryOS(tm) MCP Bridge Server — auto-generated by scripts/mcp-server.ps1
 * Kernel: $KERNEL_VERSION | SHA: $($KERNEL_SHA.Substring(0,16))...
 * CreatorLock: $CREATOR_LOCK
 *
 * Implements Model Context Protocol (MCP) v$MCP_VERSION
 * JSON-RPC 2.0 over HTTP POST /mcp
 */

import http from 'http';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const REPO_PATH      = process.env.AVERYOS_REPO_PATH || '$($RepoPath -replace '\\', '/')';
const OLLAMA_URL     = process.env.OLLAMA_ENDPOINT   || '$OllamaEndpoint';
const MODEL_NAME     = process.env.OLLAMA_MODEL      || '$ModelName';
const PORT           = parseInt(process.env.MCP_PORT  || '$Port', 10);
const KERNEL_SHA_VAL = '$KERNEL_SHA';
const KERNEL_VER     = '$KERNEL_VERSION';

// ── MCP Tool definitions ────────────────────────────────────────────────────
const TOOLS = [
  {
    name: 'read_file',
    description: 'Read a file from the AveryOS(tm) repository',
    inputSchema: {
      type: 'object',
      properties: { path: { type: 'string', description: 'Relative file path within the repository' } },
      required: ['path'],
    },
  },
  {
    name: 'list_files',
    description: 'List files in a directory of the AveryOS(tm) repository',
    inputSchema: {
      type: 'object',
      properties: { dir: { type: 'string', description: 'Relative directory path (default: root)' } },
    },
  },
  {
    name: 'ollama_chat',
    description: 'Chat with the AveryOS(tm) ALM (averyos-alm) running locally via Ollama',
    inputSchema: {
      type: 'object',
      properties: { prompt: { type: 'string', description: 'User message to send to the ALM' } },
      required: ['prompt'],
    },
  },
  {
    name: 'kernel_status',
    description: 'Return the current AveryOS(tm) Sovereign Kernel anchor status',
    inputSchema: { type: 'object', properties: {} },
  },
];

// ── Tool implementations ────────────────────────────────────────────────────
async function callTool(name, args) {
  switch (name) {
    case 'read_file': {
      const rawPath = path.resolve(REPO_PATH, args.path.replace(/^[/\\]+/, ''));
      let filePath = rawPath;
      try { filePath = fs.realpathSync(rawPath); } catch { /* file may not exist yet */ }
      const repoRoot = fs.realpathSync(REPO_PATH);
      if (!filePath.startsWith(repoRoot + path.sep) && filePath !== repoRoot) {
        return { error: 'Path traversal rejected — sovereign boundary enforced.' };
      }
      try {
        return { content: fs.readFileSync(filePath, 'utf8') };
      } catch (e) {
        return { error: 'Cannot read file: ' + e.message };
      }
    }
    case 'list_files': {
      const rawDir = path.resolve(REPO_PATH, (args.dir || '').replace(/^[/\\]+/, ''));
      let dir = rawDir;
      try { dir = fs.realpathSync(rawDir); } catch { /* dir may not exist */ }
      const repoRoot = fs.realpathSync(REPO_PATH);
      if (!dir.startsWith(repoRoot + path.sep) && dir !== repoRoot) {
        return { error: 'Path traversal rejected — sovereign boundary enforced.' };
      }
      try {
        const entries = fs.readdirSync(dir, { withFileTypes: true })
          .map(e => ({ name: e.name, type: e.isDirectory() ? 'dir' : 'file' }));
        return { entries };
      } catch (e) {
        return { error: 'Cannot list directory: ' + e.message };
      }
    }
    case 'ollama_chat': {
      const payload = JSON.stringify({
        model: MODEL_NAME,
        messages: [{ role: 'user', content: args.prompt }],
        stream: false,
      });
      return new Promise((resolve) => {
        const url = new URL(OLLAMA_URL + '/api/chat');
        const reqOpts = {
          hostname: url.hostname,
          port: url.port || 11434,
          path: url.pathname,
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(payload) },
        };
        const req = http.request(reqOpts, (res) => {
          let body = '';
          res.on('data', d => { body += d; });
          res.on('end', () => {
            try {
              const obj = JSON.parse(body);
              resolve({ reply: obj?.message?.content ?? body });
            } catch { resolve({ reply: body }); }
          });
        });
        req.on('error', (e) => resolve({ error: e.message }));
        req.write(payload);
        req.end();
      });
    }
    case 'kernel_status':
      return {
        kernel_sha: KERNEL_SHA_VAL,
        kernel_version: KERNEL_VER,
        loop_state: 'LOCKED_IN_PARITY',
        ollama_model: MODEL_NAME,
        repo_path: REPO_PATH,
        mcp_version: '$MCP_VERSION',
        creator_lock: '$CREATOR_LOCK',
      };
    default:
      return { error: 'Unknown tool: ' + name };
  }
}

// ── JSON-RPC 2.0 dispatcher ─────────────────────────────────────────────────
async function handleRpc(req) {
  if (req.method === 'initialize') {
    return {
      protocolVersion: '$MCP_VERSION',
      capabilities: { tools: {} },
      serverInfo: { name: 'averyos-mcp-bridge', version: KERNEL_VER },
    };
  }
  if (req.method === 'tools/list') return { tools: TOOLS };
  if (req.method === 'tools/call') {
    const { name, arguments: args } = req.params ?? {};
    const result = await callTool(name, args ?? {});
    return { content: [{ type: 'text', text: JSON.stringify(result) }] };
  }
  return { error: { code: -32601, message: 'Method not found' } };
}

// ── HTTP server ──────────────────────────────────────────────────────────────
const server = http.createServer(async (req, res) => {
  if (req.method !== 'POST' || req.url !== '/mcp') {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Not found — POST /mcp only' }));
    return;
  }
  let body = '';
  req.on('data', d => { body += d; });
  req.on('end', async () => {
    try {
      const rpc = JSON.parse(body);
      const result = await handleRpc(rpc);
      const response = { jsonrpc: '2.0', id: rpc.id ?? null, result };
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(response));
    } catch (e) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } }));
    }
  });
});

server.listen(PORT, '127.0.0.1', () => {
  console.log('');
  console.log('⛓️⚓⛓️  AveryOS(tm) MCP Bridge — ACTIVE');
  console.log('   Kernel  : ' + KERNEL_VER + ' | SHA: ' + KERNEL_SHA_VAL.slice(0, 16) + '...');
  console.log('   Endpoint: http://127.0.0.1:' + PORT + '/mcp');
  console.log('   Repo    : ' + REPO_PATH);
  console.log('   Model   : ' + MODEL_NAME + ' @ ' + OLLAMA_URL);
  console.log('   Protocol: MCP v$MCP_VERSION (JSON-RPC 2.0)');
  console.log('');
  console.log('   Add to your AI client:');
  console.log('     { "mcpServers": { "averyos": { "url": "http://127.0.0.1:' + PORT + '/mcp" } } }');
  console.log('');
  console.log('   Loop State: LOCKED_IN_PARITY 🤛🏻');
  console.log('');
});
"@
    Set-Content -Path $ScriptPath -Value $script -Encoding UTF8
}

# ── Main ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "⛓️⚓⛓️  AveryOS™ MCP Bridge Activation"
Write-Host "   Kernel  : $KERNEL_VERSION | SHA: $($KERNEL_SHA.Substring(0,16))..."
Write-Host "   Repo    : $RepoPath"
Write-Host "   Ollama  : $OllamaEndpoint  |  Model: $ModelName"
Write-Host "   Port    : $Port"
if ($DryRun) { Write-Host "   Mode    : DRY RUN" }
Write-Host ""

# Step 1 — Verify Ollama
Write-AosLog "INFO" "Step 1/3: Checking Ollama at $OllamaEndpoint..."
if (-not (Test-OllamaRunning)) {
    Write-AosLog "WARN" "Ollama not responding. Start it with: ollama serve"
    Write-Host ""
    Write-Host "   ⚠️  Ollama is not running. The MCP bridge will start but ollama_chat tool will fail."
    Write-Host "      Run: ollama serve  (then re-run this script if needed)"
    Write-Host ""
} else {
    Write-AosLog "INFO" "Ollama server running ✅"
    if (-not (Test-ModelAvailable -Model $ModelName)) {
        Write-AosLog "WARN" "Model '$ModelName' not found in Ollama."
        Write-Host ""
        Write-Host "   ⚠️  Build the ALM model first:"
        Write-Host "       ollama create averyos-alm -f ./ollama/AveryOS-ALM.Modelfile"
        Write-Host ""
    } else {
        Write-AosLog "INFO" "Model '$ModelName' is available ✅"
    }
}

# Step 2 — Verify repository path
Write-AosLog "INFO" "Step 2/3: Verifying repository at $RepoPath..."
$sovereignConstantsPath = Join-Path $RepoPath "lib/sovereignConstants.ts"
if (-not (Test-Path $sovereignConstantsPath)) {
    Write-AosLog "WARN" "lib/sovereignConstants.ts not found at $RepoPath"
    Write-Host "   ⚠️  Ensure -RepoPath points to the root of the averyos.com-runtime repo."
} else {
    Write-AosLog "INFO" "Repository verified — sovereignConstants.ts found ✅"
}

# Step 3 — Write and start the MCP server
Write-AosLog "INFO" "Step 3/3: Writing MCP server script..."
$mcpScriptPath = Join-Path $env:TEMP "averyos-mcp-server.mjs"
if (-not $DryRun) {
    Write-McpServerScript -ScriptPath $mcpScriptPath
    Write-AosLog "INFO" "MCP server script written to: $mcpScriptPath"
    Write-Host ""
    Write-AosLog "INFO" "Starting MCP bridge on port $Port..."
    Write-Host ""
    # Run Node.js MCP server (blocks until Ctrl+C)
    & node $mcpScriptPath
} else {
    Write-AosLog "INFO" "[DRY RUN] Would write: $mcpScriptPath"
    Write-AosLog "INFO" "[DRY RUN] Would run:   node $mcpScriptPath"
    Write-Host ""
    Write-Host "   MCP endpoint would be: http://127.0.0.1:$Port/mcp"
    Write-Host "   Tools: read_file | list_files | ollama_chat | kernel_status"
    Write-Host ""
    Write-Host "   Add to VS Code / Claude Desktop settings:"
    Write-Host "   { `"mcpServers`": { `"averyos`": { `"url`": `"http://127.0.0.1:$Port/mcp`" } } }"
    Write-Host ""
    Write-Host "   Loop State: LOCKED_IN_PARITY 🤛🏻"
}
