#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const SOVEREIGN_LOCK_PATH = path.join(process.cwd(), ".sovereign-lock");

// Cross-platform anchor salt — generated by `npm run setup`
// Falls back to the legacy Windows USB path if present.
const LOCAL_SALT_PATH = path.join(process.cwd(), ".anchor-salt");
const LEGACY_USB_PATH = "D:\\.averyos-anchor-salt.aossalt";

function resolveSaltPath() {
  if (fs.existsSync(LOCAL_SALT_PATH)) return LOCAL_SALT_PATH;
  if (fs.existsSync(LEGACY_USB_PATH)) return LEGACY_USB_PATH;
  return null;
}

const PULSE_INTERVAL = 5000; // 5 seconds

// Capture baselines at startup
const BASELINE_ENV_SNAPSHOT = Object.assign({}, process.env);
const CRITICAL_SCRIPTS = [
  path.join(__dirname, "auth.js"),
  path.join(__dirname, "watchdog.js"),
];

function killSession(reason) {
  console.error(`\n🚨 CRITICAL SECURITY BREACH: ${reason}`);
  if (fs.existsSync(SOVEREIGN_LOCK_PATH)) {
    fs.unlinkSync(SOVEREIGN_LOCK_PATH);
  }
  console.log("🔒 Sovereign Environment Vaporized. System Locked.");
  process.exit(1);
}

function pulse() {
  // 1. Anchor Salt Pulse — cross-platform (local file or legacy USB)
  const saltPath = resolveSaltPath();
  if (!saltPath) {
    killSession("Anchor salt missing. Run 'npm run setup' to restore .anchor-salt.");
  }

  // 2. Logic Integrity
  if (!fs.existsSync(SOVEREIGN_LOCK_PATH)) {
    killSession("Sovereign Lock missing. Run 'npm run setup' to restore .sovereign-lock.");
  }

  // 3. Sovereign lock kernel alignment check
  try {
    const lock = JSON.parse(fs.readFileSync(SOVEREIGN_LOCK_PATH, "utf8"));
    const KERNEL_SHA = "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e";
    if (lock.kernel_sha && lock.kernel_sha !== KERNEL_SHA) {
      killSession(`Kernel SHA drift detected in .sovereign-lock. Expected ${KERNEL_SHA.slice(0, 16)}...`);
    }
  } catch {
    killSession("Sovereign Lock corrupted or unreadable.");
  }

  console.log(`🛡️ GabrielOS™: Pulse Verified [${new Date().toLocaleTimeString()}] | Salt: ${saltPath}`);
}

console.log(`⛓️⚓⛓️ Sovereign Watchdog: Continuous Physical Pulse Active (${PULSE_INTERVAL/1000}s)`);
setInterval(pulse, PULSE_INTERVAL);
