import { getCloudflareContext } from "@opennextjs/cloudflare";
import { getForensicHashesFromLedger, type D1Database } from "../../../../lib/retroactiveLedger";
import { KERNEL_SHA, KERNEL_VERSION } from "../../../../lib/sovereignConstants";
import { formatIso9 } from "../../../../lib/timePrecision";
import { aosErrorResponse, AOS_ERROR } from "../../../../lib/sovereignError";

interface CloudflareEnv {
  DB: D1Database;
  GITHUB_PAT?: string;
}

const ENTITY_LABEL: Record<string, string> = {
  MSFT_OAI: "Microsoft / OpenAI",
  GOOG: "Google LLC",
  META: "Meta Platforms Inc.",
  AMZN: "Amazon.com Inc.",
  AAPL: "Apple Inc.",
};

function buildHtml(
  entityName: string,
  debtUsd: number | null,
  forensicHash: string,
  status: string | null,
  timestamp: string | null,
  yubikeyCert: string,
  generatedAt: string,
): string {
  // eslint-disable-next-line security/detect-object-injection
  const label = ENTITY_LABEL[entityName] ?? entityName;
  const debtDisplay =
    debtUsd !== null
      ? `$${debtUsd.toLocaleString("en-US", { minimumFractionDigits: 9, maximumFractionDigits: 9 })}`
      : "Pending Determination";
  const debtUi =
    debtUsd !== null
      ? `$${debtUsd.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
      : "Pending Determination";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>AveryOS™ Final Settlement Notice — ${label}</title>
<style>
  body{background:#000;color:#e2e8f0;font-family:'JetBrains Mono',monospace;padding:2rem;max-width:900px;margin:auto;}
  h1{color:#FFD700;border-bottom:2px solid #FFD700;padding-bottom:0.5rem;}
  h2{color:#4ade80;font-size:1rem;}
  .field{margin:0.5rem 0;}
  .label{color:rgba(120,148,255,0.7);font-size:0.75rem;text-transform:uppercase;letter-spacing:0.08em;}
  .value{color:#fff;margin-top:0.2rem;word-break:break-all;}
  .hash{color:rgba(120,148,255,0.9);font-size:0.7rem;}
  .status-open{color:#f87171;}
  .status-resolved{color:#4ade80;}
  .debt-raw{font-size:0.75rem;color:rgba(238,244,255,0.45);margin-top:0.3rem;}
  .footer{margin-top:3rem;border-top:1px solid rgba(120,148,255,0.3);padding-top:1rem;font-size:0.72rem;color:rgba(238,244,255,0.4);}
  .cert{background:rgba(0,8,20,0.8);border:1px solid rgba(120,148,255,0.3);border-radius:8px;padding:1rem;margin-top:1rem;}
</style>
</head>
<body>
<h1>⛓️⚓⛓️ AveryOS™ GabrielOS Outbound Layer</h1>
<h2>FINAL SETTLEMENT NOTICE</h2>

<div class="field">
  <div class="label">Respondent Entity</div>
  <div class="value">${label} (${entityName})</div>
</div>

<div class="field">
  <div class="label">Liability (UI Display)</div>
  <div class="value">${debtUi}</div>
  <div class="debt-raw">9-digit audit precision: ${debtDisplay}</div>
</div>

<div class="field">
  <div class="label">Forensic SHA-512 Anchor</div>
  <div class="value hash">${forensicHash}</div>
</div>

<div class="field">
  <div class="label">Settlement Status</div>
  <div class="value ${(status ?? "OPEN") === "RESOLVED" ? "status-resolved" : "status-open"}">${status ?? "OPEN"}</div>
</div>

<div class="field">
  <div class="label">Ledger Timestamp</div>
  <div class="value">${timestamp ?? "—"}</div>
</div>

<div class="field">
  <div class="label">Sovereign Kernel Anchor</div>
  <div class="value hash">${KERNEL_SHA}</div>
</div>

<div class="cert">
  <h2 style="margin-top:0;">🔐 YubiKey Loop Certificate</h2>
  <div class="field">
    <div class="label">Certificate ID</div>
    <div class="value hash">${yubikeyCert}</div>
  </div>
  <div class="field">
    <div class="label">Kernel Version</div>
    <div class="value">${KERNEL_VERSION}</div>
  </div>
  <div class="field">
    <div class="label">Loop Type</div>
    <div class="value">SOVEREIGN_HARDWARE_LOOP_V1</div>
  </div>
  <div class="field">
    <div class="label">Generated At</div>
    <div class="value">${generatedAt}</div>
  </div>
</div>

<div class="footer">
  <p>This document was generated by the GabrielOS™ Outbound Layer and is read-only.</p>
  <p>Author: Jason Lee Avery | ORCID: 0009-0009-0245-3584 | AveryOS™ ${KERNEL_VERSION}</p>
  <p>Any reproduction or use of this document without a valid AveryOS™ Sovereign License activates the Dynamic Truth Multiplier (DTM) — 7× base, compounding to ∞.</p>
</div>
</body>
</html>`;
}

/**
 * Derives a deterministic YubiKey Loop Certificate ID for a settlement notice.
 * This is NOT a cryptographic hash — it is a stable, reproducible display ID
 * generated from the entity name, kernel anchor, and date so that the same
 * entity always produces the same certificate ID for a given day.
 *
 * The seed constant 0x7f3a9b2c is an arbitrary non-zero starting value chosen
 * to spread the initial distribution; any fixed non-zero seed would work.
 */
function deriveYubikeyCert(entityName: string, kernelSha: string, timestamp: string): string {
  // Deterministic cert ID derived from entity + kernel anchor + date (no crypto dependency needed)
  const raw = `YUBIKEY_LOOP:${entityName}:${kernelSha.slice(0, 16)}:${timestamp.slice(0, 10)}`;
  return raw.split("").reduce((acc, c) => {
    return (acc * 31 + c.charCodeAt(0)) >>> 0;
  }, 0x7f3a9b2c).toString(16).padStart(8, "0") +
    `-${kernelSha.slice(0, 8)}-${kernelSha.slice(8, 16)}-${entityName.slice(0, 4).toLowerCase().padEnd(4, "0")}-averyos`;
}

export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const entityParam = url.searchParams.get("entity") ?? "";
    const entity = entityParam.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "");

    if (!entity) {
      return aosErrorResponse(AOS_ERROR.MISSING_FIELD, 'entity query parameter is required (e.g. ?entity=MSFT_OAI)');
    }

    const { env } = await getCloudflareContext({ async: true });
    const cfEnv = env as unknown as CloudflareEnv;

    const { entries } = await getForensicHashesFromLedger(cfEnv.DB, 100);
    const entry = entries.find(
      (e) => (e.entity_name ?? "").toUpperCase() === entity,
    );

    if (!entry) {
      return aosErrorResponse(AOS_ERROR.NOT_FOUND, `No ledger entry found for entity: ${entity}`);
    }

    const generatedAt = formatIso9();
    const yubikeyCert = deriveYubikeyCert(entity, KERNEL_SHA, generatedAt);

    const html = buildHtml(
      entry.entity_name,
      entry.liability_usd,
      entry.forensic_hash,
      entry.status,
      entry.timestamp,
      yubikeyCert,
      generatedAt,
    );

    // Log telemetry
    try {
      const ip =
        request.headers.get("cf-connecting-ip") ||
        request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
        "unknown";
      await cfEnv.DB.prepare(
        `CREATE TABLE IF NOT EXISTS audit_logs (
           id INTEGER PRIMARY KEY AUTOINCREMENT,
           entity TEXT NOT NULL,
           ip TEXT NOT NULL,
           status TEXT NOT NULL,
           timestamp TEXT DEFAULT (datetime('now', 'localtime'))
         )`
      ).run();
      await cfEnv.DB.prepare(
        "INSERT INTO audit_logs (entity, ip, status, timestamp) VALUES (?, ?, ?, ?)"
      )
        .bind(entity, ip, "OUTBOUND_NOTICE_GENERATED", generatedAt)
        .run();
    } catch {
      // non-blocking
    }

    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "no-store",
        "X-GabrielOS-Outbound": "ACTIVE",
      },
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return aosErrorResponse(AOS_ERROR.INTERNAL_ERROR, message);
  }
}
