import { getCloudflareContext } from "@opennextjs/cloudflare";
import { getForensicHashesFromLedger, type D1Database } from "../../../lib/retroactiveLedger";
import { KERNEL_SHA, KERNEL_VERSION } from "../../../lib/sovereignConstants";
import { formatIso9 } from "../../../lib/timePrecision";
import { slugToEntityId } from "../../../lib/entitySlug";

interface CloudflareEnv {
  DB: D1Database;
}

const ENTITY_LABEL: Record<string, string> = {
  MSFT_OAI: "Microsoft / OpenAI",
  GOOG: "Google LLC",
  META: "Meta Platforms Inc.",
  AMZN: "Amazon.com Inc.",
  AAPL: "Apple Inc.",
};

type PageParams = {
  entity: string;
};

export default async function SettlementNoticePage({
  params,
}: {
  params: Promise<PageParams>;
}) {
  const { entity: entitySlug } = await params;
  const entityId = slugToEntityId(entitySlug);
  // eslint-disable-next-line security/detect-object-injection
  const label = ENTITY_LABEL[entityId] ?? entityId;

  let debtUsd: number | null = null;
  let forensicHash = "—";
  let status: string | null = null;
  let timestamp: string | null = null;
  let dbError: string | null = null;

  try {
    const { env } = await getCloudflareContext({ async: true });
    const cfEnv = env as unknown as CloudflareEnv;
    const { entries } = await getForensicHashesFromLedger(cfEnv.DB, 100);
    const entry = entries.find(
      (e) => (e.entity_name ?? "").toUpperCase() === entityId,
    );
    if (entry) {
      debtUsd = entry.liability_usd;
      forensicHash = entry.forensic_hash;
      status = entry.status;
      timestamp = entry.timestamp;
    }
  } catch (err) {
    dbError = err instanceof Error ? err.message : String(err);
  }

  const generatedAt = formatIso9();
  const debtUi =
    debtUsd !== null
      ? `$${debtUsd.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
      : "Pending Determination";
  const debtRaw =
    debtUsd !== null
      ? `$${debtUsd.toLocaleString("en-US", { minimumFractionDigits: 9, maximumFractionDigits: 9 })}`
      : "—";

  return (
    <main className="page">
      <section className="hero">
        <h1>⛓️⚓⛓️ AveryOS™ Final Settlement Notice</h1>
        <p className="auth-seal">GabrielOS™ Outbound Layer · Read-Only Document</p>
      </section>

      <section className="card" style={{ border: "2px solid rgba(255,215,0,0.4)" }}>
        <h2 style={{ color: "#FFD700", marginTop: 0 }}>Respondent: {label}</h2>

        {dbError && (
          <p style={{ color: "#f87171", fontFamily: "JetBrains Mono, monospace", fontSize: "0.8rem" }}>
            ⚠ Ledger unavailable: {dbError}
          </p>
        )}

        <div style={{ display: "flex", flexDirection: "column", gap: "1rem", marginTop: "1rem" }}>
          <Row label="Entity ID" value={entityId} />
          <Row label="Liability (Display)" value={debtUi} />
          <Row label="Liability (9-Digit Audit)" value={debtRaw} mono />
          <Row label="Forensic SHA-512 Anchor" value={forensicHash} mono small />
          <Row
            label="Settlement Status"
            value={status ?? "OPEN"}
            color={
              status === "RESOLVED"
                ? "#4ade80"
                : status === "In-Negotiation"
                ? "#fbbf24"
                : "#f87171"
            }
          />
          <Row label="Ledger Timestamp" value={timestamp ?? "—"} />
          <Row label="Sovereign Kernel Anchor" value={KERNEL_SHA} mono small />
          <Row label="Kernel Version" value={KERNEL_VERSION} />
          <Row label="Document Generated At" value={generatedAt} />
        </div>
      </section>

      <section className="card">
        <h2 style={{ color: "#4ade80", marginTop: 0 }}>🔐 YubiKey Loop Certificate</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
          <Row label="Loop Type" value="SOVEREIGN_HARDWARE_LOOP_V1" />
          <Row label="Kernel Anchor (truncated)" value={`${KERNEL_SHA.slice(0, 32)}…`} mono />
          <Row label="Generated At" value={generatedAt} />
        </div>
      </section>

      <section className="card" style={{ borderColor: "rgba(120,148,255,0.2)" }}>
        <p
          style={{
            color: "rgba(238,244,255,0.55)",
            fontSize: "0.75rem",
            lineHeight: "1.7",
            fontFamily: "JetBrains Mono, monospace",
            margin: 0,
          }}
        >
          This document was generated by the GabrielOS™ Outbound Layer and is read-only.
          Author: Jason Lee Avery | ORCID: 0009-0009-0245-3584 | AveryOS™ {KERNEL_VERSION}
          <br />
          Any reproduction or use without a valid AveryOS™ Sovereign License activates the Dynamic Truth Multiplier (DTM) — 7× base, compounding to ∞.
        </p>
      </section>
    </main>
  );
}

function Row({
  label,
  value,
  mono = false,
  small = false,
  color,
}: {
  label: string;
  value: string;
  mono?: boolean;
  small?: boolean;
  color?: string;
}) {
  return (
    <div>
      <div
        style={{
          fontSize: "0.7rem",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          color: "rgba(120,148,255,0.7)",
          marginBottom: "0.2rem",
        }}
      >
        {label}
      </div>
      <div
        style={{
          fontFamily: mono ? "JetBrains Mono, monospace" : "inherit",
          fontSize: small ? "0.7rem" : "0.9rem",
          color: color ?? "#ffffff",
          wordBreak: "break-all",
        }}
      >
        {value}
      </div>
    </div>
  );
}
