"use client";

/**
 * app/admin/docs/page.tsx
 *
 * AveryOS™ Sovereign Documentation Explorer — Phase 108.3
 *
 * Renders the auto-generated sovereign API docs from
 * public/admin/docs/index.json. Gated behind VAULTAUTH_TOKEN verification
 * to protect IP boundaries (Gate 108.3 Secret-Scanner rule).
 *
 * Docs are generated by scripts/generate-docs.cjs on every Cloudflare build.
 *
 * ⛓️⚓⛓️  CreatorLock: Jason Lee Avery (ROOT0) 🤛🏻
 */

import { useEffect, useState } from "react";
import AnchorBanner from "../../../components/AnchorBanner";
import SovereignErrorBanner from "../../../components/SovereignErrorBanner";
import { buildAosUiError, AOS_ERROR, type AosUiError } from "../../../lib/sovereignError";
import { KERNEL_VERSION } from "../../../lib/sovereignConstants";

// ── Theme ─────────────────────────────────────────────────────────────────────

const PURPLE_DEEP   = "#0a0015";
const PURPLE_MID    = "rgba(98,0,234,0.18)";
const PURPLE_BORDER = "rgba(120,60,255,0.35)";
const GOLD          = "#ffd700";
const GOLD_BORDER   = "rgba(255,215,0,0.35)";
const WHITE         = "#ffffff";
const GREEN         = "#4ade80";

// ── Types ─────────────────────────────────────────────────────────────────────

interface DocSymbol {
  name:  string;
  kind:  string;
  doc:   string;
  file:  string;
}

interface DocsManifest {
  generated_at:  string;
  symbol_count:  number;
  kernel_version: string;
  symbols:       DocSymbol[];
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function SovereignDocsPage() {
  const [token,           setToken]           = useState("");
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);
  const [manifest,        setManifest]        = useState<DocsManifest | null>(null);
  const [search,          setSearch]          = useState("");
  const [error,           setError]           = useState<AosUiError | null>(null);
  const [loading,         setLoading]         = useState(false);

  // ── Auth check from sessionStorage ────────────────────────────────────────
  useEffect(() => {
    const stored = typeof sessionStorage !== "undefined"
      ? sessionStorage.getItem("aos_vault_token")
      : null;
    if (stored) {
      setToken(stored);
      setIsAuthenticated(true);
    } else {
      setIsAuthenticated(false);
    }
  }, []);

  // ── Load docs manifest once authenticated ────────────────────────────────
  useEffect(() => {
    if (!isAuthenticated) return;
    setLoading(true);
    fetch("/admin/docs/index.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<DocsManifest>;
      })
      .then((data) => {
        setManifest(data);
        setError(null);
      })
      .catch((err: unknown) => {
        setError(buildAosUiError(
          AOS_ERROR.EXTERNAL_API_ERROR,
          `Failed to load docs: ${err instanceof Error ? err.message : String(err)}`,
        ));
      })
      .finally(() => setLoading(false));
  }, [isAuthenticated]);

  // ── Handlers ──────────────────────────────────────────────────────────────
  function handleAuth(e: React.FormEvent) {
    e.preventDefault();
    if (!token.trim()) return;
    sessionStorage.setItem("aos_vault_token", token.trim());
    setIsAuthenticated(true);
  }

  // ── Filter ────────────────────────────────────────────────────────────────
  const filtered = manifest?.symbols.filter((s) => {
    if (!search.trim()) return true;
    const q = search.toLowerCase();
    return (
      s.name.toLowerCase().includes(q) ||
      s.file.toLowerCase().includes(q) ||
      s.doc.toLowerCase().includes(q)
    );
  }) ?? [];

  const byFile: Record<string, DocSymbol[]> = {};
  for (const sym of filtered) {
    if (!byFile[sym.file]) byFile[sym.file] = [];
    byFile[sym.file].push(sym);
  }

  // ── Render ────────────────────────────────────────────────────────────────

  if (isAuthenticated === null) {
    return (
      <main className="page" style={{ background: PURPLE_DEEP, minHeight: "100vh" }}>
        <AnchorBanner />
        <div style={{ color: GOLD, textAlign: "center", paddingTop: "4rem" }}>
          Verifying sovereign session…
        </div>
      </main>
    );
  }

  if (!isAuthenticated) {
    return (
      <main className="page" style={{ background: PURPLE_DEEP, minHeight: "100vh", padding: "2rem" }}>
        <AnchorBanner />
        <div style={{ maxWidth: 480, margin: "4rem auto", textAlign: "center" }}>
          <h1 style={{ color: GOLD, fontSize: "1.6rem", marginBottom: "0.5rem" }}>
            🔐 Sovereign Docs — Creator-Lock Gate
          </h1>
          <p style={{ color: WHITE, opacity: 0.7, marginBottom: "1.5rem", fontSize: "0.9rem" }}>
            Enter your VAULTAUTH_TOKEN to access the AveryOS™ Sovereign API Documentation.
          </p>
          <form onSubmit={handleAuth} style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
            <input
              type="password"
              placeholder="VAULTAUTH_TOKEN"
              value={token}
              onChange={(e) => setToken(e.target.value)}
              style={{
                background:  "rgba(255,255,255,0.07)",
                border:      `1px solid ${GOLD_BORDER}`,
                borderRadius: "8px",
                color:       WHITE,
                padding:     "0.75rem 1rem",
                fontSize:    "0.9rem",
                outline:     "none",
              }}
            />
            <button
              type="submit"
              style={{
                background:   GOLD,
                color:        PURPLE_DEEP,
                border:       "none",
                borderRadius: "8px",
                padding:      "0.75rem 1.5rem",
                fontWeight:   700,
                cursor:       "pointer",
                fontSize:     "1rem",
              }}
            >
              Unlock Sovereign Docs ⛓️⚓⛓️
            </button>
          </form>
        </div>

      </main>
    );
  }

  return (
    <main className="page" style={{ background: PURPLE_DEEP, minHeight: "100vh", padding: "2rem" }}>
      <AnchorBanner />

      <div style={{ maxWidth: 900, margin: "0 auto" }}>
        <h1 style={{ color: GOLD, fontSize: "1.8rem", marginBottom: "0.25rem" }}>
          AveryOS™ Sovereign API Docs
        </h1>
        <p style={{ color: WHITE, opacity: 0.55, fontSize: "0.8rem", marginBottom: "1.5rem" }}>
          {manifest
            ? `${manifest.symbol_count} symbols · Generated ${manifest.generated_at} · Kernel ${manifest.kernel_version}`
            : `Kernel ${KERNEL_VERSION}`}
        </p>

        {error && <SovereignErrorBanner error={error} />}

        {/* Search */}
        <input
          type="search"
          placeholder="Search symbols, files, docs…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          style={{
            width:        "100%",
            background:   "rgba(255,255,255,0.06)",
            border:       `1px solid ${PURPLE_BORDER}`,
            borderRadius: "8px",
            color:        WHITE,
            padding:      "0.65rem 1rem",
            fontSize:     "0.9rem",
            marginBottom: "1.5rem",
            outline:      "none",
            boxSizing:    "border-box",
          }}
        />

        {loading && (
          <p style={{ color: GOLD, opacity: 0.7, textAlign: "center" }}>
            Loading sovereign docs…
          </p>
        )}

        {!loading && manifest && filtered.length === 0 && (
          <p style={{ color: WHITE, opacity: 0.55, textAlign: "center" }}>
            No symbols match &ldquo;{search}&rdquo;.
          </p>
        )}

        {/* Symbol groups by file */}
        {Object.entries(byFile).map(([file, syms]) => (
          <section
            key={file}
            style={{
              background:    PURPLE_MID,
              border:        `1px solid ${PURPLE_BORDER}`,
              borderRadius:  "12px",
              padding:       "1.25rem",
              marginBottom:  "1.25rem",
            }}
          >
            <h2
              style={{
                color:         GOLD,
                fontSize:      "0.85rem",
                fontFamily:    "JetBrains Mono, monospace",
                marginBottom:  "0.75rem",
                wordBreak:     "break-all",
              }}
            >
              📄 {file}
            </h2>

            {syms.map((sym) => (
              <div
                key={sym.name}
                style={{
                  borderTop:   `1px solid ${GOLD_BORDER}`,
                  paddingTop:  "0.6rem",
                  marginTop:   "0.6rem",
                }}
              >
                <div style={{ display: "flex", alignItems: "baseline", gap: "0.5rem", marginBottom: "0.25rem" }}>
                  <span
                    style={{
                      color:      GREEN,
                      fontFamily: "JetBrains Mono, monospace",
                      fontSize:   "0.9rem",
                      fontWeight: 700,
                    }}
                  >
                    {sym.name}
                  </span>
                  <span
                    style={{
                      color:      GOLD_BORDER,
                      fontSize:   "0.75rem",
                      fontFamily: "JetBrains Mono, monospace",
                    }}
                  >
                    ({sym.kind})
                  </span>
                </div>
                {sym.doc && (
                  <p
                    style={{
                      color:      WHITE,
                      opacity:    0.75,
                      fontSize:   "0.8rem",
                      margin:     0,
                      lineHeight: 1.5,
                    }}
                  >
                    {sym.doc}
                  </p>
                )}
              </div>
            ))}
          </section>
        ))}

        {/* Gold rule footer */}
        <div
          style={{
            textAlign:   "center",
            marginTop:   "2rem",
            paddingTop:  "1rem",
            borderTop:   `1px solid ${GOLD_BORDER}`,
            color:       GOLD,
            fontSize:    "0.75rem",
            opacity:     0.6,
          }}
        >
          ⛓️⚓⛓️ AveryOS™ Sovereign Integrity License v1.0 · CreatorLock: Jason Lee Avery 🤛🏻
        </div>
      </div>


    </main>
  );
}
