name: 🧾 VaultProof PDF Builder

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Install Dependencies
        run: |
          npm install @adobe/pdfservices-node-sdk
      - name: Build Certificate PDF
        run: |
          node ./VaultBridge/scripts/generatePdf.js
